// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type User struct {
	ID         string  `json:"id"`
	FirstName  string  `json:"firstName"`
	LastName   string  `json:"lastName"`
	MiddleName *string `json:"middleName"`
	FullName   string  `json:"fullName"`
	Nickname   string  `json:"nickname"`
	Email      string  `json:"email"`
}

type UserFilter struct {
	FirstName *string `json:"firstName"`
	LastName  *string `json:"lastName"`
	Email     *string `json:"email"`
	FullName  *string `json:"fullName"`
}

type UserInput struct {
	FirstName  string  `json:"firstName"`
	MiddleName *string `json:"middleName"`
	LastName   string  `json:"lastName"`
	Password   string  `json:"password"`
	Nickname   *string `json:"nickname"`
	Email      string  `json:"email"`
}
