package errorConstants

import "errors"

var (
	ErrUserAlreadyLoggedIn           = errors.New("user is already logged in")
	ErrUserNotLoggedIn               = errors.New("user is not logged in")
	ErrUserBadPassword               = errors.New("bad password")
	ErrUserWeakPassword              = errors.New("password does not meet the requirements")
	ErrUserNicknameAlreadyUsed       = errors.New("user with specified nickname already exists")
	ErrUserEmailAlreadyUsed          = errors.New("user with specified e-mail already exists")
	ErrUserInputNotContainsAllProps  = errors.New("user input does not contain all required properties")
	ErrUserEmailWrong                = errors.New("specified e-mail is wrong")
	ErrUserEmailTooShort             = errors.New("specified e-mail is too short")
	ErrUserEmailTooLong              = errors.New("specified e-mail is too long")
	ErrUserFirstNameTooShort         = errors.New("specified first name is too short")
	ErrUserFirstNameTooLong          = errors.New("specified last name is too long")
	ErrUserLastNameTooShort          = errors.New("specified last name is too short")
	ErrUserLastNameTooLong           = errors.New("specified last name is too long")
	ErrUserMiddleNameTooShort        = errors.New("specified middle name is too short")
	ErrUserMiddleNameTooLong         = errors.New("specified middle name is too long")
	ErrUserPasswordTooShort          = errors.New("specified password is too short")
	ErrUserPasswordTooLong           = errors.New("specified password is too long")
	ErrUserNicknameTooShort          = errors.New("specified nickname is too short")
	ErrUserNicknameTooLong           = errors.New("specified nickname is too long")
	ErrNoUserWithSpecifiedEmail      = errors.New("there is no user with the specified e-mail")
	ErrNoUserWithSpecifiedId         = errors.New("there is no user with specified id")
	ErrNoUserWithSpecifiedNickname   = errors.New("there is no user with specified nickname")
	ErrInvalidID                     = errors.New("invalid id")
	ErrChangePasswordTokenNotFound   = errors.New("invalid token")
	ErrChangePasswordSameNewPassword = errors.New("specified new password is the same as old password")
	ErrChatAlreadyCreated            = errors.New("chat is already created")
)
